version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5100:5100"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=your_secret_key

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
