version: "3.8"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret

  backend:
    build: ./backend
    ports:
      - "5100:5100"
    volumes:
      - ./backend:/app # Bind mount local directory to /app in container
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=your_secret_key
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app # Maps the frontend directory to /app in the container
      - /app/node_modules # Keeps node_modules on the container to avoid override by the bind mount
    environment:
      - CHOKIDAR_USEPOLLING=true # Enables polling for file changes
      - CHOKIDAR_INTERVAL=1000 # Sets the polling interval to 1000ms
    depends_on:
      - backend
