version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5100:5100"
    volumes:
      - ./backend:/app # Bind mount local directory to /app in container
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=your_secret_key
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app # Maps the frontend directory to /app in the container
      - /app/node_modules # Keeps node_modules on the container to avoid override by the bind mount
    environment:
      - CHOKIDAR_USEPOLLING=true # Enables polling for file changes
      - CHOKIDAR_INTERVAL=1000 # Sets the polling interval to 1000ms
    depends_on:
      - backend

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres # Default PostgreSQL user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testing # Name of the default database
